# Generated by Django 4.2.4 on 2023-08-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_teams_team_member_teams_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to='ID_Cards'),
        ),
    ]
