# Generated by Django 4.2.4 on 2023-09-01 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_students_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('event', 'student')},
        ),
    ]
