# Generated by Django 4.2.4 on 2023-09-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_registration_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='Event_Banners'),
        ),
        migrations.AddField(
            model_name='events',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='Event_Posters'),
        ),
    ]
