# Generated by Django 4.2.4 on 2023-09-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_events_banner_events_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
