# Generated by Django 4.2.4 on 2023-09-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_events_category'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('student', 'event'), name='unique_payment_for_student_and_event'),
        ),
    ]
