# Generated by Django 4.2.4 on 2023-10-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_events_reg_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
    ]
